#

In [6]:
import pandas as pd

In [20]:
pole = pd.read_csv('modified_pokemon.csv')

In [21]:
df

,Pokemon Name,Primary Type,Secondary Type,Secondary Ability,Base Happiness,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total
0,"""Bulbasaur""","""Grass""","""Poison""",NaN,50,"""Red""",45,49,49,65,65,45,318
1,"""Ivysaur""","""Grass""","""Poison""",NaN,50,"""Red""",60,62,63,80,80,60,405
2,"""Venusaur""","""Grass""","""Poison""",NaN,50,"""Red""",80,82,83,100,100,80,525
3,"""Venusaur""","""Grass""","""Poison""",NaN,70,"""X""",80,100,123,122,120,80,625
4,"""Venusaur""","""Grass""","""Poison""",NaN,50,"""Sword""",80,82,83,100,100,80,525
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""",NaN,0,"""Scarlet""",90,72,100,122,108,98,590
1378,"""Terapagos""","""Normal""",NaN,NaN,0,"""Violet""",160,105,110,130,110,85,700
1379,"""Terapagos""","""Normal""",NaN,NaN,0,"""Violet""",90,65,85,65,85,60,450
1380,"""Terapagos""","""Normal""",NaN,NaN,0,"""Scarlet""",95,95,110,105,110,85,600
1381,"""Pecharunt""","""Poison""","""Ghost""",NaN,0,"""Scarlet""",88,88,160,88,88,88,600

In [23]:
#Eliminar la columna 'Secondary hahbility'
df=df.drop('Secondary Ability', axis=1)

In [24]:
df

,Pokemon Name,Primary Type,Secondary Type,Base Happiness,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total
0,"""Bulbasaur""","""Grass""","""Poison""",50,"""Red""",45,49,49,65,65,45,318
1,"""Ivysaur""","""Grass""","""Poison""",50,"""Red""",60,62,63,80,80,60,405
2,"""Venusaur""","""Grass""","""Poison""",50,"""Red""",80,82,83,100,100,80,525
3,"""Venusaur""","""Grass""","""Poison""",70,"""X""",80,100,123,122,120,80,625
4,"""Venusaur""","""Grass""","""Poison""",50,"""Sword""",80,82,83,100,100,80,525
...,...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""",0,"""Scarlet""",90,72,100,122,108,98,590
1378,"""Terapagos""","""Normal""",NaN,0,"""Violet""",160,105,110,130,110,85,700
1379,"""Terapagos""","""Normal""",NaN,0,"""Violet""",90,65,85,65,85,60,450
1380,"""Terapagos""","""Normal""",NaN,0,"""Scarlet""",95,95,110,105,110,85,600
1381,"""Pecharunt""","""Poison""","""Ghost""",0,"""Scarlet""",88,88,160,88,88,88,600

In [25]:
#Eliminar la columna 'Base Happiness' Etc
df=df.drop('Base Happiness', axis=1)

In [26]:
df

,Pokemon Name,Primary Type,Secondary Type,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total
0,"""Bulbasaur""","""Grass""","""Poison""","""Red""",45,49,49,65,65,45,318
1,"""Ivysaur""","""Grass""","""Poison""","""Red""",60,62,63,80,80,60,405
2,"""Venusaur""","""Grass""","""Poison""","""Red""",80,82,83,100,100,80,525
3,"""Venusaur""","""Grass""","""Poison""","""X""",80,100,123,122,120,80,625
4,"""Venusaur""","""Grass""","""Poison""","""Sword""",80,82,83,100,100,80,525
...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""","""Scarlet""",90,72,100,122,108,98,590
1378,"""Terapagos""","""Normal""",NaN,"""Violet""",160,105,110,130,110,85,700
1379,"""Terapagos""","""Normal""",NaN,"""Violet""",90,65,85,65,85,60,450
1380,"""Terapagos""","""Normal""",NaN,"""Scarlet""",95,95,110,105,110,85,600
1381,"""Pecharunt""","""Poison""","""Ghost""","""Scarlet""",88,88,160,88,88,88,600

In [28]:
df.to_csv('modified_pokemon_noGens.csv', index=False)

In [6]:
pokedb = pd.read_csv('modified_pokemon_noGens.csv')

In [30]:
pokedb

,Pokemon Name,Primary Type,Secondary Type,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total
0,"""Bulbasaur""","""Grass""","""Poison""","""Red""",45,49,49,65,65,45,318
1,"""Ivysaur""","""Grass""","""Poison""","""Red""",60,62,63,80,80,60,405
2,"""Venusaur""","""Grass""","""Poison""","""Red""",80,82,83,100,100,80,525
3,"""Venusaur""","""Grass""","""Poison""","""X""",80,100,123,122,120,80,625
4,"""Venusaur""","""Grass""","""Poison""","""Sword""",80,82,83,100,100,80,525
...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""","""Scarlet""",90,72,100,122,108,98,590
1378,"""Terapagos""","""Normal""",NaN,"""Violet""",160,105,110,130,110,85,700
1379,"""Terapagos""","""Normal""",NaN,"""Violet""",90,65,85,65,85,60,450
1380,"""Terapagos""","""Normal""",NaN,"""Scarlet""",95,95,110,105,110,85,600
1381,"""Pecharunt""","""Poison""","""Ghost""","""Scarlet""",88,88,160,88,88,88,600

In [84]:
#Comprovar cuants jocs hi ha
games = df['Game(s) of Origin'].drop_duplicates() 
print(games)

0                    "Red"
3                      "X"
4                  "Sword"
23            "Omega Ruby"
29                   "Sun"
38      "Let's Go Pikachu"
86        "Legends Arceus"
192              "Scarlet"
229                 "Gold"
309                 "Ruby"
532             "Fire Red"
533           "Leaf Green"
534              "Emerald"
535              "Diamond"
645             "Platinum"
668                "Black"
840              "Black 2"
1018           "Ultra Sun"
1097          "PokÃ©mon GO"
1374              "Violet"
Name: Game(s) of Origin, dtype: object

In [87]:
#Funcio per asignar una gen a cada joc de pokemon
def asignar_generacion(df):
    Gen = {
        'Red' : 'Gen1',
        'X' : 'Gen6',
        'Sword' : 'Gen8',
        'Omega Ruby' : 'Gen6',
        'Sun' : 'Gen7',
        'Let\'s Go Pikachu' : 'Gen7',
        'Legends Arceus' : 'Gen8',
        'Scarlet' : 'Gen9',
        'Gold' : 'Gen2',
        'Ruby' : 'Gen3',
        'Fire Red' : 'Gen3',
        'Leaf Green' : 'Gen3',
        'Emerald' : 'Gen3',
        'Diamond' : 'Gen4',
        'Platinum' : 'Gen4',
        'Black' :  'Gen5',
        'Black 2' : 'Gen5',
        'Ultra Sun' : 'Gen7',
        'PokÃ©mon GO' : 'Gen7',
        'Violet' : 'Gen9',
    }
    df['Gen'] = df['Game(s) of Origin'].apply(lambda x: Gen.get(x.strip('"').strip(), 'GeneraciÃ³n desconocida'))    
    return df

In [88]:
#Executar la funcio
pokedb = asignar_generacion(pokedb)

In [89]:
pokedb

,Pokemon Name,Primary Type,Secondary Type,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Gen
0,"""Bulbasaur""","""Grass""","""Poison""","""Red""",45,49,49,65,65,45,318,Gen1
1,"""Ivysaur""","""Grass""","""Poison""","""Red""",60,62,63,80,80,60,405,Gen1
2,"""Venusaur""","""Grass""","""Poison""","""Red""",80,82,83,100,100,80,525,Gen1
3,"""Venusaur""","""Grass""","""Poison""","""X""",80,100,123,122,120,80,625,Gen6
4,"""Venusaur""","""Grass""","""Poison""","""Sword""",80,82,83,100,100,80,525,Gen8
...,...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""","""Scarlet""",90,72,100,122,108,98,590,Gen9
1378,"""Terapagos""","""Normal""",NaN,"""Violet""",160,105,110,130,110,85,700,Gen9
1379,"""Terapagos""","""Normal""",NaN,"""Violet""",90,65,85,65,85,60,450,Gen9
1380,"""Terapagos""","""Normal""",NaN,"""Scarlet""",95,95,110,105,110,85,600,Gen9
1381,"""Pecharunt""","""Poison""","""Ghost""","""Scarlet""",88,88,160,88,88,88,600,Gen9

In [90]:
#Comprovar la columna Gen
generations = pokedb['Gen'].drop_duplicates()
print(generations)

0      Gen1
3      Gen6
4      Gen8
29     Gen7
192    Gen9
229    Gen2
309    Gen3
535    Gen4
668    Gen5
Name: Gen, dtype: object

In [4]:
pokedb.to_csv('modified_pokemon_withGens.csv', index=False)

NameError: name 'pokedb' is not defined

In [7]:
pokedb

,Pokemon Name,Primary Type,Secondary Type,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Gen
0,"""Bulbasaur""","""Grass""","""Poison""","""Red""",45,49,49,65,65,45,318,Gen1
1,"""Ivysaur""","""Grass""","""Poison""","""Red""",60,62,63,80,80,60,405,Gen1
2,"""Venusaur""","""Grass""","""Poison""","""Red""",80,82,83,100,100,80,525,Gen1
3,"""Venusaur""","""Grass""","""Poison""","""X""",80,100,123,122,120,80,625,Gen6
4,"""Venusaur""","""Grass""","""Poison""","""Sword""",80,82,83,100,100,80,525,Gen8
...,...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""","""Scarlet""",90,72,100,122,108,98,590,Gen9
1378,"""Terapagos""","""Normal""",NaN,"""Violet""",160,105,110,130,110,85,700,Gen9
1379,"""Terapagos""","""Normal""",NaN,"""Violet""",90,65,85,65,85,60,450,Gen9
1380,"""Terapagos""","""Normal""",NaN,"""Scarlet""",95,95,110,105,110,85,600,Gen9
1381,"""Pecharunt""","""Poison""","""Ghost""","""Scarlet""",88,88,160,88,88,88,600,Gen9

In [7]:
pokedb = pd.read_csv('modified_pokemon_withGens.csv')

In [8]:
pokedb

,Pokemon Name,Primary Type,Secondary Type,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Gen
0,"""Bulbasaur""","""Grass""","""Poison""","""Red""",45,49,49,65,65,45,318,Gen1
1,"""Ivysaur""","""Grass""","""Poison""","""Red""",60,62,63,80,80,60,405,Gen1
2,"""Venusaur""","""Grass""","""Poison""","""Red""",80,82,83,100,100,80,525,Gen1
3,"""Venusaur""","""Grass""","""Poison""","""X""",80,100,123,122,120,80,625,Gen6
4,"""Venusaur""","""Grass""","""Poison""","""Sword""",80,82,83,100,100,80,525,Gen8
...,...,...,...,...,...,...,...,...,...,...,...,...
1377,"""Iron Crown""","""Steel""","""Psychic""","""Scarlet""",90,72,100,122,108,98,590,Gen9
1378,"""Terapagos""","""Normal""",NaN,"""Violet""",160,105,110,130,110,85,700,Gen9
1379,"""Terapagos""","""Normal""",NaN,"""Violet""",90,65,85,65,85,60,450,Gen9
1380,"""Terapagos""","""Normal""",NaN,"""Scarlet""",95,95,110,105,110,85,600,Gen9
1381,"""Pecharunt""","""Poison""","""Ghost""","""Scarlet""",88,88,160,88,88,88,600,Gen9

In [11]:
# Definir la funciÃ³ per agafar els 6 pokemons mes poderosos per generacio
def millor_pokemon_per_generacio(df, gen):
    
    generacio = df[df['Gen'] == gen]
    totalEstadistiques = generacio.sort_values(by='Base Stat Total', ascending=False)
    top6 = totalEstadistiques.head(6)
    print(top6)
    
    #return top6

In [12]:
#Comprovacio amb la gen1
millor_pokemon = millor_pokemon_per_generacio(pokedb, 'Gen1')

    Pokemon Name Primary Type Secondary Type Game(s) of Origin  Health Stat  \
225     "Mewtwo"    "Psychic"            NaN             "Red"          106
228        "Mew"    "Psychic"            NaN             "Red"          100
224  "Dragonite"     "Dragon"       "Flying"             "Red"           91
220    "Moltres"       "Fire"       "Flying"             "Red"           90
216   "Articuno"        "Ice"       "Flying"             "Red"           90
218     "Zapdos"   "Electric"       "Flying"             "Red"           90

     Attack Stat  Defense Stat  Special Attack Stat  Special Defense Stat  \
225          110            90                  154                    90
228          100           100                  100                   100
224          134            95                  100                   100
220          100            90                  125                    85
216           85           100                   95                   125
218           90            85                  125                    90

     Speed Stat  Base Stat Total   Gen
225         130              680  Gen1
228         100              600  Gen1
224          80              600  Gen1
220          90              580  Gen1
216          85              580  Gen1
218         100              580  Gen1

In [13]:
#Comprovacio amb la gen 9
millor_pokemon = millor_pokemon_per_generacio(pokedb, 'Gen9')

      Pokemon Name Primary Type Secondary Type Game(s) of Origin  Health Stat  \
1378   "Terapagos"     "Normal"            NaN          "Violet"          160
1356    "Koraidon"   "Fighting"       "Dragon"         "Scarlet"          100
1357    "Miraidon"   "Electric"       "Dragon"         "Scarlet"          100
1308     "Palafin"      "Water"            NaN         "Scarlet"          100
1381   "Pecharunt"     "Poison"        "Ghost"         "Scarlet"           88
1372  "Archaludon"      "Steel"       "Dragon"         "Scarlet"           90

      Attack Stat  Defense Stat  Special Attack Stat  Special Defense Stat  \
1378          105           110                  130                   110
1356          135           115                   85                   100
1357           85           100                  135                   115
1308          160            97                  106                    87
1381           88           160                   88                    88
1372          105           130                  125                    65

      Speed Stat  Base Stat Total   Gen
1378          85              700  Gen9
1356         135              670  Gen9
1357         135              670  Gen9
1308         100              650  Gen9
1381          88              600  Gen9
1372          85              600  Gen9